Download other GitHubs

diff --git a/get_code_cov b/get_code_cov
--- a/get_code_cov
+++ b/get_code_cov
@@ -1,7 +1,11 @@
 #!/bin/bash
-# Get the code coverage on Travis CI
+GCOV_EXE=gcov-5 # gcov and g++ versions must match
+OBJ_FILES_PATH=.
 
-for filename in `find . | egrep "^.*\.cpp$" | egrep -v "^ribi_main.cpp$" | egrep -v "^.*_test.cpp$"`; 
-do 
-  gcov-5 -n -o . $filename 
-done
+if [ ! -d "$OBJ_FILES_PATH" ]
+then
+  echo "Object file path not found at "$OBJ_FILES_PATH
+  exit 1
+fi
+
+for filename in `find . | egrep '\.cpp'`; do $GCOV_EXE -o $OBJ_FILES_PATH $filename > /dev/null; done
